# Generated by Django 2.2.6 on 2023-06-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CAN', 'Cancelled'), ('BOOK', 'Booked'), ('NEW', 'New')], default='NEW', max_length=4),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='The number of actual tickets available upon creation'),
        ),
    ]
